### PR TITLE
docs small re-organization

### PR DESCRIPTION
**Pull request by kkdao**
Just some restructuring, and small additions and changes before translating all the docs.

### CODE REVIEW

**Comment by odudex** [comment]
Nice improvements!
As discussed in TG group, I'll wait for you to merge Tadeu's fix for accidental Embit and Maixpy changes.

**Comment by jdlcdl** [comment]
https://github.com/selfcustody/krux/pull/409/commits/5cc06d7fd04ddddc99820174789ef68f1f20e004 looks to have resolved embit/MaixPy inclusion.

**Comment by tadeubas** [comment]
Yes but the branch still has conflits with develop... I think it is the changes I've made to some docs that @kkdao made too. I will solve the merge and submit another PR to @kkdao

**Comment by tadeubas** [comment]
Done @kkdao , just accept my PR: https://github.com/kkdao/krux/pull/2

**Comment by odudex** [comment]
Thank you!

**Pull request merged**
