### PR TITLE
Sign base64 PSBTs From SD card

### PR DESCRIPTION
**Pull request by odudex**
### Description

When the SD PSBT signing was optimized, it lost the ability to work with base64 encoded PSBTs. @tadeubas caught this bug, which affects PSBTs exported by Blue Wallet as base64 text. This PR addresses the issue by altering the parsing and saving processes to correctly handle base64 data.

### What is the purpose of this pull request? 

- [X] Bug fix
- [ ] New Feature
- [ ] Documentation update
- [ ] Other

### CODE REVIEW

**Comment by tadeubas** [comment]
Did a few tests that worked on my end

**Comment by tadeubas** [comment]
But we have to check these broken tests:
 ```
FAILED tests/pages/home_pages/test_home.py::test_sign_psbt - ValueError: Error loading PSBT file: Invalid PSBT magic
FAILED tests/pages/home_pages/test_home.py::test_psbt_warnings - ValueError: Error loading PSBT file: Invalid PSBT magic
FAILED tests/pages/home_pages/test_home.py::test_sign_p2tr_zeroes_fingerprint - ValueError: Error loading PSBT file: Invalid PSBT magic
FAILED tests/test_psbt.py::test_init_singlesig_from_sdcard - ValueError: Error loading PSBT file: Invalid PSBT magic
FAILED tests/test_psbt.py::test_init_multisig_from_sdcard - ValueError: Error loading PSBT file: Invalid PSBT magic
FAILED tests/test_psbt.py::test_sign_singlesig_from_sdcard - ValueError: Error loading PSBT file: Invalid PSBT magic
FAILED tests/test_psbt.py::test_sign_multisig_from_sdcard - ValueError: Error loading PSBT file: Invalid PSBT magic
```

**Comment by odudex** [comment]
Yes, tomorrow I'll keep working on it. Fell free to modify/optimize too!

**Comment by jdlcdl** [comment]
As of fd42157,

This branch is working for me.

As @odudex noted in chat, to enable ".txt" files, since sparrow defaults a base64 filename like "TxSendLabel.psbt.txt" would be an improvement, otherwise krux won't find the psbt file on sdcard.  Because bip174 hints that ".psbt" is in binary format, I also prefer ".txt" for base64.

**Comment by jdlcdl** [comment]
As of 88c2599,

Working for me, as well as with very intuitive filename extensions and ".txt" supported.

**Comment by tadeubas** [comment]
just for record, BW exports the `.psbt` file but in B64 mode, so we can't assume it is just `.txt` that uses this format.

**Comment by odudex** [comment]
As it is, it will open .psbt, .psbt.txt, and .txt files. I will save the file with its original extension unless it is .txt, in which case it will be replaced with .psbt.txt.

**Pull request merged**
