### PR TITLE
docs small changes

### PR DESCRIPTION
**Pull request by kkdao**

### CODE REVIEW

**Comment by tadeubas** [comment]
The doc changes seems fine for me, the only thing I don't understand is why Github is showing changes on MaixPy submodule, but when clicking to see the changes, it shows nothing changed... @odudex maybe there is something incorrectly configured on the repository or maybe it is just a Github error

image

**Comment by tadeubas** [comment]
It is just that @kkdao is using the MAIN branch of selfcustody:MaixPy (commit 85dba62), but you is using your FORK from selfcustody:MaixPy (commit be183c2). So accepting this commit will only change the link of the submodule (nothing changes on MaixPy itself)

selfcustody:MaixPy
image

odudex:MaixPy
image

**Comment by odudex** [comment]
We have some changes in a pending PR to Maixpy. I think I'll merge the PR to reduce this and other issues caused by having these different versions in different repositories. I would wait to do it together with the new release, but as these Maixpy PR won't cause problems for someone building the current release I thin I can update it now.

**Comment by odudex** [comment]
@kkdao, I cherry picked your changes, then replaced the `single-key` term for `single-sig` in another files, including the firmware. @tadeubas, I created "develop_rc" branch on Maixpy as well and pointed krux to pull from it. I'll close this PR, but your contribution was merged through cherry-pick.
We still have a lot to document :grimacing:

**Pull request closed without merging**
