### PR TITLE
Updated mind maps to better reflect the actual navigation (v24.07.0)

### PR DESCRIPTION
**Pull request by tadeubas**
Updated mind maps to better reflect the actual navigation (v24.07.0)

### What is the purpose of this pull request? 

- [ ] Bug fix
- [ ] New Feature
- [X] Documentation update
- [ ] Other

### CODE REVIEW

**Comment by odudex** [comment]
Did you noticed I change this yesterday? Either way, yours have good ideas

**Comment by tadeubas** [comment]
Yes I noticed! I've reviewed all entries and found some details missing and updated my mind map!

**Comment by odudex** [comment]
Right.
Can you just remove the "EXIT" from the login path. It makes sense for us as developers who know the code but may confuse users.

**Comment by tadeubas** [comment]
Sure, I've had another ideas and changed it a little, plz can you check again?

Login:
https://gitmind.com/app/docs/mhy2zxnu

Home:
https://gitmind.com/app/docs/m6ajxvli

**Comment by odudex** [comment]
Looks good! Thank you!

**Pull request merged**
