### PR TITLE
 Tests adapted to new code, touch improved

### PR DESCRIPTION
**Pull request by odudex**
Tests and main code adjustments.
Did more tests on touch/I2C, saw some rare exceptions and "gagging" were yet occurring, so I studied IC specs and improved the driver by setting appropriated registers and methods.
Added a script that joins .bdf to .dkz font conversion in a single step

### CODE REVIEW

**Comment by odudex** [comment]
On the effort of increasing tests coverage I'm having a hard time trying to switch between two `board`s on tests.
This is important to reach the `touch.py`, `BUTTON C` and other exclusive parts of the code.
I tried to use this in a separated file `test_input_amigo.py`:
```
if "board" in sys.modules:
    del sys.modules["board"]
sys.modules["board"] = board_amigo()
```
But it won't have any effect if inside a method, or, will have effect on other files, even the ones tested earlier, if outside a method.
Do you have any suggestion?

**Comment by odudex** [comment]
Just to keep you up, I'm on 94% coverage :sweat_smile:
Also tried to run simulator, it wasn't able to load embit module. Any tip on how to run it in a neat way?

**Comment by jreesun** [comment]
@odudex embit should be installed and available for tests by running `poetry install`. See here for how the CI installs dependencies and runs the tests: https://github.com/selfcustody/krux/blob/main/.github/workflows/tests.yml#L80-L87

**Comment by odudex** [comment]
Noticed power button as page prev went automatically here, I think you should let this commit out while MaixPy is not updated

**Comment by jreesun** [comment]
Sorry for the delay, been busy lately. Hoping to review this and your other PR (against MaixPy) over the weekend

**Comment by odudex** [comment]
Ok Jeff, I'll start tinkering with passphrase keypad(s)

**Comment by jreesun** [comment]
@odudex 
Sorry for the radio silence, some other things unfortunately have had to take priority over this project recently. 

I had some follow-up work I wanted to add to `develop`, cleaning up some code and getting tests passing, then I was going to work on updating the website to be less M5-specific and include information about the Amigo, with screencaps.

Going to set aside a week to focus on that shortly; aiming for a July release that includes all your Amigo work!

**Comment by odudex** [comment]
Also did some cleanup, main was a keypad class.

You can take a look:
https://github.com/odudex/krux

Em qui, 23 de jun de 2022 18:27, Eduardo Schoenknecht <
***@***.***> escreveu:

**Comment by odudex** [comment]
Don't worry Jeff,
Later we can catch on the changes.
I had all test passing and coverage > 95% with my "passphrase" commit.

Recently I made another board compatible, Maix Dock. And used a rotary
encoder on it. Got really good.

When you come back we talk more.

Em qui, 23 de jun de 2022 18:19, Jeff ***@***.***> escreveu:

**Pull request merged**
