### PR TITLE
Issues templates and dependabot configuration

### PR DESCRIPTION
**Pull request by qlrd**
### Description

This PR adds 3 more Issue templates (`documentation`, `good first issue` and `question`) and a dependabot.yml configuration to check for updates for used github-actions and pip packages.

### What is the purpose of this pull request? 

- [ ] Bug fix
- [ ] New Feature
- [ ] Documentation update
- [x] Other: issue templates and dependabot for CI/CD

### CODE REVIEW

**Comment by odudex** [comment]
I didn't get what a "Good first issue" would be, and how a first issue wouldn't be a another type of issue (bug, feature request, etc).
For dependabot, it is already active on Github's project security management tab, I think to add and maintain a custom configuration file is not necessary. (Current packages which raise dependabot warnings were already updated on "integrated_changes" branch)

**Comment by qlrd** [comment]
Sorry for delay @odudex 😳

> I didn't get what a "Good first issue" would be, and how a first issue wouldn't be a another type of issue (bug, feature request, etc).

I understand that a `Good first issue` tag maybe help new devs that want to contribute to krux but do not know where or how to start. But maybe its ok to not add;

> For dependabot, it is already active on Github's project security management tab, I think to add and maintain a custom configuration file is not necessary.

Yes, the only difference is that a configuration file can setup the a periodically auto-check with auto-open PRs with these found changes. These aren't a strict needed one for CI, only wanted to share a workflow that i use in `krux-installer` and `krux-file-signer`.

Feel free to close this PR if that's the case.

**Comment by odudex** [comment]
I like the first issue is a useful tag(or label), but is it necessary a dedicated template?
About dependabot, to fix its last warnings it required a short investigation, module replacement and code adaptation, so I don't think automatic PRs would help, I consider current notifications the ideal form of interaction.
The other templates are fine for me. If you could remove the auto-open PR thing we could merge it.

**Comment by qlrd** [comment]
> I like the first issue is a useful tag(or label), but is it necessary a dedicated template?

Yeah, you're right... maybe a dedicated template isn't necessary.

>  If you could remove the auto-open PR thing we could merge it.

Based on [docs](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates#disabling-dependabot-version-updates), i think that is possible and customizable. 

Proposal:

- Enable updates only for when a `github-action` is updated; e.g, when `docker/buildx-action@v2` changes to `docker/setup-buildx-action@v3` in [this step](https://github.com/selfcustody/krux/blob/main/.github/workflows/build.yml#L27C15-L27C44);

- disable updates on `pip` to(by putting `open-pull-requests-limit: 0` option) on it;

**Pull request closed without merging**
